### PR TITLE
Create TestRunner.yml

### PR DESCRIPTION
**Pull request by kjsong10**
This will automatically run the test cases on push and pull requests targeting main branch.

### CODE REVIEW

**Comment by kjsong10** [comment]
I used the directory that Tyler had for his test cases in his branch.

**Review by Myan02 — APPROVED** [review]
it looks good, just make sure to address the one error in the check

**Comment by tort8678** [comment]
Sweet, looks good. The tests I uploaded may not be passing though... But auto running the tests in that folder is exactly what we need. Good work.

**Review by tort8678 — APPROVED** [review]
Sweet, looks good. The tests I uploaded may not be passing though... But auto running the tests in that folder is exactly what we need. Good work.

**Pull request merged**
