### PR TITLE
SFX effects

### PR DESCRIPTION
**Pull request by dimoselika**
SFX effect

### CODE REVIEW

**Comment by msierras** [comment]
SFX works when walking and settings menu allows for SFX volume change. Looks good to me!

**Review by msierras — COMMENTED** [review]
SFX works when walking and settings menu allows for SFX volume change. Looks good to me!

**Review by msierras — APPROVED** [review]
SFX works when walking and settings menu allows for SFX volume change. Looks good to me!

**Comment by tort8678** [comment]
Nice, I like the sound. Make sure to document where you got it from.

**Review by tort8678 — APPROVED** [review]
Nice, I like the sound. Make sure to document where you got it from.

**Pull request merged**
